package common

// originally generated by ChatGPT

type Queue[T any] []T

// NewQueue creates a new queue.
func NewQueue[T any]() *Queue[T] {
	return &Queue[T]{}
}

// NewQueueFromArray creates a new queue starting with the given items.
func NewQueueFromArray[T any](items []T) *Queue[T] {
	q := make(Queue[T], len(items))
	copy(q, items)
	return &q
}

// Enqueue adds an item to the end of the queue.
func (q *Queue[T]) Enqueue(item T) {
	*q = append(*q, item)
}

// Dequeue removes and returns the first item in the queue.
func (q *Queue[T]) Dequeue() T {
	item := (*q)[0]
	*q = (*q)[1:]
	return item
}

// IsEmpty returns true if the queue is empty.
func (q *Queue[T]) IsEmpty() bool {
	return len(*q) == 0
}

func (q *Queue[T]) Count() int {
	return len(*q)
}

func (q *Queue[T]) PeekAt(index int) T {
	return (*q)[index]
}

func (q *Queue[T]) RemoveAt(index int) {
	*q = append((*q)[:index], (*q)[index+1:]...)
}

func (q *Queue[T]) UpdateAt(index int, item T) {
	(*q)[index] = item
}

func (q *Queue[T]) CloneFront(count int) *Queue[T] {
	return NewQueueFromArray((*q)[:count])
}
